# Generated by Django 5.2.8 on 2025-11-29 17:57

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('size_mb', models.CharField(max_length=20)),
                ('SD_format', models.BooleanField(null=True)),
                ('HD_format', models.BooleanField(null=True)),
                ('dp', models.URLField()),
                ('screenshot1', models.URLField()),
                ('screenshot2', models.URLField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('SD_link', models.URLField(blank=True, max_length=500, null=True)),
                ('HD_link', models.URLField(blank=True, max_length=500, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
