# Generated by Django 5.2.8 on 2025-11-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='dp',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movies',
            name='screenshot1',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movies',
            name='screenshot2',
            field=models.URLField(max_length=500),
        ),
    ]
