# Generated by Django 5.2.8 on 2025-11-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_dp_alter_movies_screenshot1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='HD_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='HD_telegram_file_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='SD_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='SD_telegram_file_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
