# Generated by Django 5.2.8 on 2025-11-30 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movies_hd_message_id_movies_hd_telegram_file_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('file_id', models.CharField(help_text='The Telegram file ID for the file to be downloaded.', max_length=200)),
                ('quality', models.CharField(choices=[('SD', 'Standard Definition'), ('HD', 'High Definition')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='movies.movies')),
            ],
        ),
    ]
