# Generated by Django 5.2.8 on 2025-11-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_downloadtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadtoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='downloadtoken',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='downloadtoken',
            name='quality',
        ),
        migrations.AlterField(
            model_name='downloadtoken',
            name='file_id',
            field=models.CharField(max_length=200),
        ),
    ]
