# Generated by Django 5.2.8 on 2025-11-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_downloadtoken_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadtoken',
            name='file_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movies',
            name='HD_telegram_file_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='SD_telegram_file_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
