# Generated by Django 5.2.8 on 2025-11-30 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_downloadtoken_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadtoken',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movies'),
        ),
        migrations.AddField(
            model_name='downloadtoken',
            name='quality',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
