# Generated by Django 5.2.8 on 2025-12-01 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_downloadtoken_movie_downloadtoken_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('quality', models.CharField(max_length=5)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delete_at', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['delete_at'], name='movies_sent_delete__5e10f4_idx'), models.Index(fields=['chat_id', 'message_id'], name='movies_sent_chat_id_38bdf3_idx')],
            },
        ),
    ]
