# Generated by Django 5.2.8 on 2025-12-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_sentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
