# Generated by Django 5.2.8 on 2025-12-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movies_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='type',
            field=models.CharField(choices=[('movies', 'Movies'), ('tv', 'TV Shows'), ('anime', 'Anime')], default='movies', max_length=20),
        ),
    ]
