# Generated by Django 5.2.8 on 2025-12-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_merge_20251210_0657'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='directdownloadtoken',
            new_name='movies_dire_token_6de314_idx',
            old_name='movies_dire_token_idx',
        ),
        migrations.RenameIndex(
            model_name='directdownloadtoken',
            new_name='movies_dire_expires_d6d1c7_idx',
            old_name='movies_dire_expires_idx',
        ),
        migrations.AddField(
            model_name='movies',
            name='trailer',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
